# This is a basic workflow to help you get started with Actions

name: Workflow-onedrive-automatization

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *' # Todos os dias após baixar os Encartes colocar na pasta do onedrive.

jobs:
  build:
    runs-on: windows-latest

    steps:
    #Check atual repository
      - name: Checkout repository 
        uses: actions/checkout@v4

    #Setup Python Environment with cache  
      - name: Setup Python (com cache)
        uses: actions/setup-python@v5
        with:
         python-version: "3.5"
         cache: "pip"
         cache-dependency-path: requirements.txt

    #Install dependencies with python
      - name: Instalar dependencias
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    #Download all files from artifacts (supermercados-code) 
      - name: Download files on supermercados-code
        uses: actions/download-artifact@v4
        with:
         working-directory: workflow-github-action

    #Setup OneDrive Autentication and Environment
      - name: Setup OneDrive Autentication
        uses: actions/checkout@v4
        env:
          ONEDRIVE_CLIENT_ID: ${{ secrets.ONEDRIVE_CLIENT_ID }}
          ONEDRIVE_CLIENT_SECRET: ${{ secrets.ONEDRIVE_CLIENT_SECRET }}
          ONEDRIVE_CLIENT_TOKEN: ${{ secrets.ONEDRIVE_CLIENT_TOKEN }}
          ONEDRIVE_FOLDER: https://grupomateus-my.sharepoint.com/:f:/r/personal/guilherme_macedo_grupomateus_com/Documents/RELATORIOS%20MKT%20-%20TESTE?csf=1&web=1&e=sn945v
      
    #Run command to run scripts (Main Function)
      - name: Main Function
        run: |
         echo "Estes são os arquivos artifacts"
         mkdir output
         echo "Arquivos" > artifacts.txt
         python.exe upload_to_onedrive.py artifacts.txt output/artifacts_output.txt
         echo "Arquivos baixados com sucesso" 
