# This is a basic workflow to help you get started with Actions

name: Workflow-onedrive-automatization

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *' # Todos os dias após baixar os Encartes colocar na pasta do onedrive.

jobs:
  build:
    runs-on: windows-lastest

    steps:
      - name: Checkout repository 
      - uses: actions/checkout@v4

      - name: Setup Ubuntu Envrionment
      - run: |
         sudo apt-get update
         sudo apt-get install -y onedrive
        
      # Runs a single command using the runners shell
      - name: Download files on supermercados-code
        shell: pwsh
        uses: actions/download-artifact@v4
        working-directory: workflow-github-action

      - name: Setup OneDrive Autentication
         uses:
         ONEDRIVE_CLIENT_ID: ${{ secrets.ONEDRIVE_CLIENT_ID }}
         ONEDRIVE_CLIENT_SECRET: ${{ secrets.ONEDRIVE_CLIENT_SECRET }}
         ONEDRIVE_CLIENT_TOKEN: ${{ secrets.ONEDRIVE_CLIENT_TOKEN }}
         ONEDRIVE_FOLDER: https://grupomateus-my.sharepoint.com/:f:/r/personal/guilherme_macedo_grupomateus_com/Documents/RELATORIOS%20MKT%20-%20TESTE?csf=1&web=1&e=sn945v

      - name: Setup Envrionment
      - run: |
         echo "Estes são os arquivos artifacts"
         mkdir output
         echo "Arquivos" > artifacts.txt
         python.exe upload_to_onedrive.py artifacts.txt output/artifacts_output.txt
         echo "Arquivos baixados com sucesso" 
