name: Workflow-onedrive-automatization

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'  # 10:00 America/Fortaleza

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout (este repo)
        uses: actions/checkout@v4

      # Baixa artifacts do outro repositório
      - name: Download artifacts from supermercados-code
        uses: dawidd6/action-download-artifact@v6
        with:
          repo: solutionsmateus/workflow-github-action
          workflow: vm-solutions-mateus.yml
          branch: main
          name: "*"                            # todos os artifacts deste run
          path: artifacts
          if_no_artifact_found: warn
          token: ${{ secrets.MEUPAT }}

      #Lista todos os artifacts baixados.
      - name: List downloaded artifacts
        shell: pwsh
        run: |
          echo "Conteúdo de artifacts:"
          Get-ChildItem -Recurse artifacts | Select-Object FullName, Length

      #Instalar rclone
      - name: Install rclone
        shell: pwsh
        run: choco install rclone -y


      - name: Restore rclone.conf from base64 secret (Windows path)
        shell: pwsh
        env:
          RCLONE_CONF_B64: ${{ secrets.RCLONE_CONF_B64 }}
        run: |
          $confDir = Join-Path $env:APPDATA 'rclone'
          New-Item -ItemType Directory -Force -Path $confDir | Out-Null
          $confPath = Join-Path $confDir 'rclone.conf'
          # Decodifica base64 preservando quebras de linha
          [IO.File]::WriteAllBytes($confPath, [Convert]::FromBase64String($env:RCLONE_CONF_B64))
          # Checagens
          rclone listremotes
          rclone config show

      - name: Upload artifacts to OneDrive
        shell: pwsh
        env:
          ONEDRIVE_FOLDER_PATH: "Shared/Grupo Mateus/Guilherme Soares de Macedo/RELATORIOS MKT - TESTE/"
        run: |
          # Opcional: validar acesso antes
          rclone lsd onedrive:
          rclone lsd ("onedrive:" + $env:ONEDRIVE_FOLDER_PATH)

          rclone copy "artifacts" ("onedrive:" + $env:ONEDRIVE_FOLDER_PATH) `
            --progress --transfers=8 --checkers=16 --create-empty-src-dirs
