name: Workflow-onedrive-automatization

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'  # 10:00 America/Fortaleza

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout (este repo)
        uses: actions/checkout@v4

      # Baixa artifacts do outro repositório
      - name: Download artifacts from supermercados-code
        uses: dawidd6/action-download-artifact@v6
        with:
          repo: solutionsmateus/workflow-github-action
          workflow: vm-solutions-mateus.yml
          branch: main
          name: "*"                      
          path: artifacts
          if_no_artifact_found: warn
          token: ${{ secrets.MEUPAT }}

      #Lista todos os artifacts baixados.
      - name: Drive the files to ZIP.
        shell: pwsh
        run: |
          echo "Conteúdo de artifacts:"
          Get-ChildItem -Recurse artifacts | Select-Object FullName, Length



  
