name: Workflow-onedrive-automatization

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'  # 10:00 America/Fortaleza

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout (este repo)
        uses: actions/checkout@v4

      # Baixa artifacts do outro repositório
      - name: Download artifacts from supermercados-code
        uses: dawidd6/action-download-artifact@v6
        with:
          repo: solutionsmateus/supermercados-code
          workflow: vm-solutions-mateus
          branch: main
          name: "*"                            # todos os artifacts deste run
          path: artifacts
          if_no_artifact_found: warn

      - name: List downloaded artifacts
        shell: pwsh
        run: |
          echo "Conteúdo de artifacts:"
          Get-ChildItem -Recurse artifacts | Select-Object FullName, Length

      # Instala rclone
      - name: Install rclone
        shell: pwsh
        run: choco install rclone -y

      # Restaura o rclone.conf a partir do Secret
      - name: Write rclone.conf from secret
        shell: pwsh
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
        run: |
          $confDir = "$env:USERPROFILE\.config\rclone"
          New-Item -ItemType Directory -Force -Path $confDir | Out-Null
          Set-Content -Path (Join-Path $confDir "rclone.conf") -Value $env:RCLONE_CONFIG
          # Valida a remota
          rclone config show

      # Copia tudo da pasta artifacts para a pasta no OneDrive
      - name: Upload artifacts to OneDrive
        shell: pwsh
        env:
          ONEDRIVE_FOLDER_PATH: "RELATORIOS MKT - TESTE"   # ajuste o caminho
        run: |
          # "onedrive:" é o nome da remota criada no rclone config
          rclone copy "artifacts" ("onedrive:" + $env:ONEDRIVE_FOLDER_PATH) `
            --progress --transfers=8 --checkers=16 --create-empty-src-dirs
